### ISSUE TITLE
Any planned update?

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/ArticleManager#6]
Any planned update for this module?

**Comment by Nicola1971** [comment]
Yes but too much big to do now.. (I want add new features and design restyle)
Note: I need a final evo 1.4 to find some free time to update a lot of extras.
Actually my free time is dedicated to evo 1.4 dev, flat theme and the flat system settings plugin.. 
and you are my greatest help to test and fix the flat theme 😄

**Comment by Nicola1971** [comment]
maybe a replacement for ArticleManager?

https://github.com/Nicola1971/DashboardListDoc-widget
![doclist333](https://user-images.githubusercontent.com/7342798/33715917-865d2b64-db54-11e7-9eba-89f12b368be5.png)

**Comment by risingisland** [comment]
Almost. 
Closing this thread, will comment on my observations in ListDoc.
